### ISSUE TITLE
Pig the Dice 게임 로직 구현

### ISSUE THREAD

**Issue by ja960508** [STFE5/test-repo#2]
### 목적
주사위를 굴려 나온 수로 현재 플레이어의 점수를 집계한다.

### Tasks
- [x] 주사위 굴리기 기능(random 1 ~ 6)
- [x] 현재 점수 기록 변수
- [x] Roll, Stop 행동에 따른 이벤트(Roll 결과가 1이면 점수 초기화, Stop이면 현재까지 얻은 점수 추가, 각 기능 후 턴 종료)
- [x] 가장 먼저 100점인 플레이어가 승리

**Comment by ulgoon** [comment]
Awesome!
