### ISSUE TITLE
컴퓨터의 게임 진행 알고리듬 구현

### ISSUE THREAD

**Issue by Goat95** [STFE5/test-repo#5]
## 목적
컴퓨터의 게임 진행 알고리듬은 Roll을 1회 이상 진행하는 Random 진행으로 적용

## Tasks

- [x] 컴퓨터 턴에 Roll을 바로 진행
- [x] Random으로 Roll 혹은 Stop 진행
- [x] 주사위 1이 나오면 턴 종료

**Comment by ulgoon** [comment]
Well done!
